### ISSUE TITLE
Exception in ReadChunk

### ISSUE THREAD

**Issue by hippogamesunity** [martinhodler/unity-aseprite-importer#33]
**Describe the bug**
Hi! Got an exception inside ReadChunk when loading some specific aseprite file. At the same time, Aseprite can open that file.
You can get this file here https://drive.google.com/file/d/137kFAqRVqGeH8X-hXmCrvTbYhD-2A3V_/view?usp=sharing

**Comment by hippogamesunity** [comment]
![image](https://user-images.githubusercontent.com/7318172/93492664-ba173780-f913-11ea-8d38-a3614aa45c56.png)

**Comment by martinhodler** [comment]
Sorry for the late reaction... school was taking over.
Thanks for the bug report. There was an error in the Aseprite-Reader in the CelExtraChunk class to be more specific. Instead of reading floats from the file it read doubles which caused the EndOfStreamException.

This error was fixed with the commit e8b0396.

**Comment by hippogamesunity** [comment]
Thanks, it works now!
