### ISSUE TITLE
Missing namespaces in 1.03 version

### ISSUE THREAD

**Issue by RevengerWizard** [martinhodler/unity-aseprite-importer#39]
So, I tried to import the newest version (the 1.03) of the package, but got 4 error messages of missing namespaces. Here an image:

![image](https://user-images.githubusercontent.com/64542915/103317857-cc356580-4a2c-11eb-8885-65c0430944f6.png)

**Comment by martinhodler** [comment]
Which version of unity were you using?

**Comment by martinhodler** [comment]
Looks like the issue is in versions before 2020.2. Unity moved the ScriptedImporter with all its classes from the Experimental namespace to the new UnityEditor.AssetImporters namespace.
I fixed the missing namespaces for unity versions before the 2020.2 update with these two commits.
c21693f666689346f73f3258d35edc779cb2d612
30ee30bf0c4e87d1ecdb04011ebf221d794bec33

**Comment by RevengerWizard** [comment]
Yea, I'm using the Unity 2019.4.13f and now everything works fine, thanks!
