### ISSUE TITLE
Ase file incorrect size detected

### ISSUE THREAD

**Issue by p10tr3k** [martinhodler/unity-aseprite-importer#40]
**Describe the bug**
For attached file which size is 224x240, importer detects size 512x512. The image is incorrectly imported.
Importer: Bundled (preview)

**To Reproduce**
Just import attached file

**Screenshots**
This image 
![image](https://user-images.githubusercontent.com/11059246/103447553-19177700-4c8d-11eb-945a-dc7111bda5b1.png)
is imported like this
![image](https://user-images.githubusercontent.com/11059246/103447542-e79eab80-4c8c-11eb-9b87-be9973d131e7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2020.1.4f1

[test.zip](https://github.com/martinhodler/unity-aseprite-importer/files/5759535/test.zip)

**Comment by p10tr3k** [comment]
This is proposed fix. But I may misunderstand usage of this extension so the fix could be wrong

**Comment by martinhodler** [comment]
Hi @p10tr3k thanks for your help. The issue was with the Atlas calculation. It only supported sprites that have the same height and width.
Now i changed the method to calculate columns and rows for the sprites to create a texture which should mostly create a quadratic atlas.
I commited these changes to your pull request and I'm going to integrate it with those changes.

Let me know if the changes fixed your issue.
